table Product

	column Brand
		dataType: string
		summarizeBy: none
		sourceColumn: Brand

		annotation SummarizationSetBy = Automatic

	column Category
		dataType: string
		summarizeBy: none
		sourceColumn: Category

		annotation SummarizationSetBy = Automatic

	column Color
		dataType: string
		summarizeBy: none
		sourceColumn: Color

		annotation SummarizationSetBy = Automatic

	column Manufacturer
		dataType: string
		summarizeBy: none
		sourceColumn: Manufacturer

		annotation SummarizationSetBy = Automatic

	column 'Product Code'
		dataType: string
		summarizeBy: none
		sourceColumn: Product Code

		annotation SummarizationSetBy = Automatic

	column 'Product Name'
		dataType: string
		summarizeBy: none
		sourceColumn: Product Name

		annotation SummarizationSetBy = Automatic

	column ProductKey
		dataType: int64
		isHidden
		summarizeBy: none
		sourceColumn: ProductKey

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Subcategory
		dataType: string
		summarizeBy: none
		sourceColumn: Subcategory

		annotation SummarizationSetBy = Automatic

	hierarchy Category-Subcategory

		level Category
			column: Category

		level Subcategory
			column: Subcategory

	partition Product = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(File.Contents("pbi-tools/contoso-sales-model/main/data/Promotion.xlsx"), null, true),
				    # "the real sheet" = Source{[Item="sheet_name]}[Data],
				    #"Promoted Headers" = Table.PromoteHeaders("the real sheet", [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"ProductKey", Int64.Type}, {"Product Code", type text}, {"Product Name", type text}, {"Manufacturer", type text}, {"Brand", type text}, {"Subcategory", type text}, {"Category", type text}, {"Color", type text}})
				in
				    #"Changed Type"

